name: micromall CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: master  # 切换到master分支
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set SSH Environment
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
        echo "${{ secrets.ID_RSA_PUB }}" > ~/.ssh/id_rsa.pub
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/id_rsa
        chmod 700 ~/.ssh && chmod 700 ~/.ssh/*
        ls -l ~/.ssh/
    - name: Download config file and replace
      run: |
          git clone git@github.com:gujiniCY/micromall_prod_configuration.git
          mv -f ./micromall_prod_configuration/dev_config/application.yml ./micromall-all/src/main/resources/application.yml
    - name: Build Java jar
      run: |
          mvn clean install
    - name: Move files and compress
      run: |
          mkdir -p transfer_files
          mv ./micromall-all/target/micromall-all.jar ./transfer_files/micromall-all.jar
    - name: Scp file to aliyun
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.NAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "transfer_files.tar.gz"
        target: "/home"
    - name: Distribution and backup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.NAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd /home
            tar -zxvf /home/transfer_files.tar.gz

            echo "################# micromall-all moving #################"

            if [ -f "/home/micromall/micromall-all/micromall-all.jar.bak" ];then
              echo "micromall-all.jar.bak exists and is being deleted"
              rm -f /home/micromall/micromall-all/micromall-all.jar.bak
            fi
            mv /home/transfer_files/micromall-all.jar /home/micromall/micromall-all/micromall-all.jar
    - name: Start micromall-all
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.NAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/micromall/micromall-all/
          ./shutdown.sh
          ./startup.sh
